---
version: '3.7'

#THIS environment sets up all of MEDS
#  All dependencies -> HSM (vault), RTS (Redfish sims) are all setup and active.
#  The ports are exposed to the local system.
networks:
  meds:

services:
  #
  # Vault
  # 
  vault:
    hostname: vault
    image: artifactory.algol60.net/docker.io/library/vault:1.5.5
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=hms
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - meds
  vault-kv-enabler:
    image: artifactory.algol60.net/csm-docker/stable/vault-kv-enabler:1.13.4
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - KV_STORES=hms-creds,reds-creds,secret
    depends_on:
      - vault
    networks:
      - meds

  #
  # SLS
  #
  cray-sls-postgres:
    hostname: sls-postgres
    image: artifactory.algol60.net/docker.io/library/postgres:11-alpine
    environment:
      - POSTGRES_USER=slsuser
      - POSTGRES_DB=sls
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "54321:5432"
    networks:
      - meds
  cray-sls-init:
    image: artifactory.algol60.net/csm-docker/stable/cray-sls:1.16.0
    command: ["sls-init"]
    environment:
      - POSTGRES_HOST=sls-postgres
      - DBOPTS=sslmode=disable
      - DBUSER=slsuser
    depends_on:
      - cray-sls-postgres
    networks:
      - meds
  cray-sls:
    image: artifactory.algol60.net/csm-docker/stable/cray-sls:1.16.0
    environment:
      - POSTGRES_HOST=cray-sls-postgres
      - DBOPTS=sslmode=disable
      - DBUSER=slsuser
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
    ports:
      - "8376:8376"
    depends_on:
      - cray-sls-postgres
      - cray-sls-init
      - vault
    networks:
      - meds

  cray-sls-preload:
    image: artifactory.algol60.net/csm-docker/stable/cray-sls:1.16.0
    command: >
      sh -c "sleep 5 &&
      curl  -d '{\"Xname\":\"x1000\",\"Type\":\"comptype_cabinet\",\"Class\":\"Mountain\",\"TypeString\":\"Cabinet\",\"ExtraProperties\":{\"Networks\":{\"cn\":{
        \"HMN\":{\"CIDR\":\"10.104.0.1/22\",\"Gateway\":\"10.104.3.254\",\"VLan\":3001},
        \"NMN\":{\"CIDR\":\"10.100.0.1/22\",\"Gateway\":\"10.100.3.254\",\"VLan\":2001}},
        \"ncn\":{}}}}' http://cray-sls:8376/v1/hardware"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DBOPTS=sslmode=disable
      - DBUSER=slsuser
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
    depends_on:
      - cray-sls
    networks:
      - meds

  #
  # HSM
  #
  cray-smd-postgres:
    hostname: hmsds-postgres
    image: artifactory.algol60.net/docker.io/library/postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=hmsdsuser
      - POSTGRES_USER=hmsdsuser
      - POSTGRES_DB=hmsds
    ports:
      - "54322:5432"
    networks:
      - meds
  cray-smd-init:
    image: artifactory.algol60.net/csm-docker/stable/cray-smd:1.48.0
    environment:
      - SMD_DBHOST=cray-smd-postgres
      - SMD_DBPORT=5432
    depends_on:
      - cray-smd-postgres
    networks:
      - meds
    command: /entrypoint.sh smd-init
  cray-smd:
    image: artifactory.algol60.net/csm-docker/stable/cray-smd:1.48.0
    environment:
      - POSTGRES_HOST=cray-smd-postgres
      - SMD_DBHOST=cray-smd-postgres
      - POSTGRES_PORT=5432
      - RF_MSG_HOST=kafka:9092:cray-dmtf-resource-event
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
      - SMD_WVAULT=true
      - SMD_RVAULT=true
    hostname: cray-smd
    depends_on:
      - cray-smd-init
      - vault
    ports:
      - "27779:27779"
    networks:
      - meds

  #
  # RTS
  #

  #
  # MEDS
  #
  meds-init:
    build:
      context: .
    command: ["vault_loader"]
    environment:
      - HSM_URL=http://cray-smd:27779/hsm/v1
      - MEDS_OPTS=""
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
      - VAULT_SKIP_VERIFY=true
      - MEDS_NTP_TARG=""
      - MEDS_SYSLOG_TARG=""
      - MEDS_NP_RF_URL="/redfish/v1/Managers/BMC/NetworkProtocol"
      - MEDS_ROOT_SSH_KEY=""
    networks:
      - meds
  meds:
    build:
      context: .
    environment:
      - HSM_URL=http://cray-smd:27779/hsm/v1
      - "MEDS_OPTS=-sls http://cray-sls:8376/v1"
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
      - VAULT_SKIP_VERIFY=true

      - MEDS_SYSLOG_TARG=localhost:514
      # - MEDS_SYSLOG_TARG_USE_IP=
      - MEDS_NTP_TARG=localhost:123
      # - MEDS_NTP_TARG_USE_IP=
      - MEDS_CA_URI=

      # - MEDS_NTP_TARG="time-hmn:123"
      # - MEDS_SYSLOG_TARG="rsyslog-aggregator.hmnlb:514"
      # - MEDS_NP_RF_URL=/redfish/v1/Managers/BMC/NetworkProtocol
      # - MEDS_ROOT_SSH_KEY=""
    volumes: 
      - ./configs:/configs
    networks:
      - meds
    depends_on:
      - cray-sls-init
      - cray-sls
      - cray-sls-preload
      - vault

  # dummy-endpoint:
  #   build:
  #     context: tests/dummy-endpoint
  #     dockerfile: Dockerfile.dummy-endpoint.Dockerfile.Dockerfile
  #   hostname: x1000c1s1b0
  #   environment:
  #     - SCHEMA_VERSION=2019.1
  #     - LOG_LEVEL=TRACE
  #   ports:
  #     - "443:443"
  #   networks:
  #     meds:
  #       aliases:
  #         - x1000c1s1b0
