# Copyright 2019-2020 Hewlett Packard Enterprise Development LP

FROM cray/meds-base

# Run unit tests...
RUN set -ex && \
    go test -v stash.us.cray.com/HMS/hms-meds/cmd/meds && \
    go test -v stash.us.cray.com/HMS/hms-meds/internal/model
