---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meds-nwproto-info
data:
  NTP_HOST: "{{ .Values.ntpserver_host }}"

---
apiVersion: v1
data:
  options: ""
kind: ConfigMap
metadata:
  name: meds-opts

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meds-cacert-info
data:
  CA_URI: "{{ .Values.hms_ca_uri }}"

